### ISSUE TITLE
Empty list of resources

### ISSUE THREAD

**Issue by RailWar** [VELD-Dev/riftripper#1]
In **File/Open game** files I selected the file **RiftApart.exe** . And I got empty list.

ExeFile RiftApart.exe, version 1.831.0.0, size 106361464

<details><summary>Log</summary>

Is extension associated ? False - False
Folder found: E:\Games\Ratchet and Clank - Rift Apart, must check if it's a game.
Game is Ratchet & Clank: Rift Apart.
Started reading TOC and DAG files.
Checking TOC and DAG existence.
TOC and DAG files exist, started reading those.
Started reading TOC file.
Started reading a DAT1 file.
[o:0x8] Peeking 0x4 bytes at +0x0 (0x8)
Magic read for DAT1 Header.
[o:0x8] Peeking 0x4 bytes at +0x4 (0xC)
DAT1 Header - ID: 4D7CF320
[o:0x8] Peeking 0x4 bytes at +0x8 (0x10)
DAT1 Header - Length: 12574420 (BFDED4)
[o:0x8] Peeking 0x4 bytes at +0xC (0x14)
DAT1 Header - Sections count: 8 (8)
Reading DAT1 section at offset 10
[o:0x10] Peeking 0x4 bytes at +0x0 (0x10)
DAT1 Section - ID: BFDED4
[o:0x10] Peeking 0x4 bytes at +0x4 (0x14)
DAT1 Section - Offset: 8 (8)
[o:0x10] Peeking 0x4 bytes at +0x8 (0x18)
DAT1 Section - Length: 36A6C8CC (916900044)
DAT1 Section - End: 36A6C8D4 (916900052)
Added section BFDED4 to sections dictionary.
Reading DAT1 section at offset 1C
[o:0x1C] Peeking 0x4 bytes at +0x0 (0x1C)
DAT1 Section - ID: 7CEF70
[o:0x1C] Peeking 0x4 bytes at +0x4 (0x20)
DAT1 Section - Offset: 186B0 (100016)
[o:0x1C] Peeking 0x4 bytes at +0x8 (0x24)
DAT1 Section - Length: 398ABFF0 (965394416)
DAT1 Section - End: 398C46A0 (965494432)
Added section 7CEF70 to sections dictionary.
Reading DAT1 section at offset 28
[o:0x28] Peeking 0x4 bytes at +0x0 (0x28)
DAT1 Section - ID: 7CC980
[o:0x28] Peeking 0x4 bytes at +0x4 (0x2C)
DAT1 Section - Offset: 25E6 (9702)
[o:0x28] Peeking 0x4 bytes at +0x8 (0x30)
DAT1 Section - Length: 506D7B8A (1349352330)
DAT1 Section - End: 506DA170 (1349362032)
Added section 7CC980 to sections dictionary.
Reading DAT1 section at offset 34
[o:0x34] Peeking 0x4 bytes at +0x0 (0x34)
DAT1 Section - ID: 880
[o:0x34] Peeking 0x4 bytes at +0x4 (0x38)
DAT1 Section - Offset: 2995A8 (2725288)
[o:0x34] Peeking 0x4 bytes at +0x8 (0x3C)
DAT1 Section - Length: 62297090 (1646882960)
DAT1 Section - End: 62530638 (1649608248)
Added section 880 to sections dictionary.
Reading DAT1 section at offset 40
[o:0x40] Peeking 0x4 bytes at +0x0 (0x40)
DAT1 Section - ID: 8C3250
[o:0x40] Peeking 0x4 bytes at +0x4 (0x44)
DAT1 Section - Offset: 4 (4)
[o:0x40] Peeking 0x4 bytes at +0x8 (0x48)
DAT1 Section - Length: 654BDED9 (1699471065)
DAT1 Section - End: 654BDEDD (1699471069)
Added section 8C3250 to sections dictionary.
Reading DAT1 section at offset 4C
[o:0x4C] Peeking 0x4 bytes at +0x0 (0x4C)
DAT1 Section - ID: 8C3260
[o:0x4C] Peeking 0x4 bytes at +0x4 (0x50)
DAT1 Section - Offset: 33AC74 (3386484)
[o:0x4C] Peeking 0x4 bytes at +0x8 (0x54)
DAT1 Section - Length: 65BCF461 (1706882145)
DAT1 Section - End: 65F0A0D5 (1710268629)
Added section 8C3260 to sections dictionary.
Reading DAT1 section at offset 58
[o:0x58] Peeking 0x4 bytes at +0x0 (0x58)
DAT1 Section - ID: 299E30
[o:0x58] Peeking 0x4 bytes at +0x4 (0x5C)
DAT1 Section - Offset: 532B50 (5450576)
[o:0x58] Peeking 0x4 bytes at +0x8 (0x60)
DAT1 Section - Length: C9FB9DDA (3388710362)
DAT1 Section - End: CA4EC92A (3394160938)
Added section 299E30 to sections dictionary.
Reading DAT1 section at offset 64
[o:0x64] Peeking 0x4 bytes at +0x0 (0x64)
DAT1 Section - ID: 7E7620
[o:0x64] Peeking 0x4 bytes at +0x4 (0x68)
DAT1 Section - Offset: DBC30 (900144)
[o:0x64] Peeking 0x4 bytes at +0x8 (0x6C)
DAT1 Section - Length: EDE8ADA9 (3991449001)
DAT1 Section - End: EDF669D9 (3992349145)
Added section 7E7620 to sections dictionary.
Started reading DAG file.
Started reading a DAT1 file.
[o:0xC] Peeking 0x4 bytes at +0x0 (0xC)
Magic read for DAT1 Header.
[o:0xC] Peeking 0x4 bytes at +0x4 (0x10)
DAT1 Header - ID: 2A077A51
[o:0xC] Peeking 0x4 bytes at +0x8 (0x14)
DAT1 Header - Length: 19105440 (12386A0)
[o:0xC] Peeking 0x4 bytes at +0xC (0x18)
DAT1 Header - Sections count: 6 (6)
Reading DAT1 section at offset 10
[o:0x10] Peeking 0x4 bytes at +0x0 (0x10)
DAT1 Section - ID: 2A077A51
[o:0x10] Peeking 0x4 bytes at +0x4 (0x14)
DAT1 Section - Offset: 12386A0 (19105440)
[o:0x10] Peeking 0x4 bytes at +0x8 (0x18)
DAT1 Section - Length: 6 (6)
DAT1 Section - End: 12386A6 (19105446)
Added section 2A077A51 to sections dictionary.
Reading DAT1 section at offset 1C
[o:0x1C] Peeking 0x4 bytes at +0x0 (0x1C)
DAT1 Section - ID: 7A0266BC
[o:0x1C] Peeking 0x4 bytes at +0x4 (0x20)
DAT1 Section - Offset: FD5500 (16602368)
[o:0x1C] Peeking 0x4 bytes at +0x8 (0x24)
DAT1 Section - Length: 2951D (169245)
DAT1 Section - End: FFEA1D (16771613)
Added section 7A0266BC to sections dictionary.
Reading DAT1 section at offset 28
[o:0x28] Peeking 0x4 bytes at +0x0 (0x28)
DAT1 Section - ID: 933C0D32
[o:0x28] Peeking 0x4 bytes at +0x4 (0x2C)
DAT1 Section - Offset: DE5790 (14571408)
[o:0x28] Peeking 0x4 bytes at +0x8 (0x30)
DAT1 Section - Length: 14A8E8 (1353960)
DAT1 Section - End: F30078 (15925368)
Added section 933C0D32 to sections dictionary.
Reading DAT1 section at offset 34
[o:0x34] Peeking 0x4 bytes at +0x0 (0x34)
DAT1 Section - ID: BC91D1CC
[o:0x34] Peeking 0x4 bytes at +0x4 (0x38)
DAT1 Section - Offset: 10A3EA0 (17448608)
[o:0x34] Peeking 0x4 bytes at +0x8 (0x3C)
DAT1 Section - Length: 187E64 (1605220)
DAT1 Section - End: 122BD04 (19053828)
Added section BC91D1CC to sections dictionary.
Reading DAT1 section at offset 40
[o:0x40] Peeking 0x4 bytes at +0x0 (0x40)
DAT1 Section - ID: BFEC699F
[o:0x40] Peeking 0x4 bytes at +0x4 (0x44)
DAT1 Section - Offset: 122BD10 (19053840)
[o:0x40] Peeking 0x4 bytes at +0x8 (0x48)
DAT1 Section - Length: C990 (51600)
DAT1 Section - End: 12386A0 (19105440)
Added section BFEC699F to sections dictionary.
Reading DAT1 section at offset 4C
[o:0x4C] Peeking 0x4 bytes at +0x0 (0x4C)
DAT1 Section - ID: D101A6CC
[o:0x4C] Peeking 0x4 bytes at +0x4 (0x50)
DAT1 Section - Offset: F30080 (15925376)
[o:0x4C] Peeking 0x4 bytes at +0x8 (0x54)
DAT1 Section - Length: A5474 (676980)
DAT1 Section - End: FD54F4 (16602356)
Added section D101A6CC to sections dictionary.
This section is not supported yet.
</details>

**Comment by VELD-Dev** [comment]
Hi!
Thanks for the interest you give to the Riftripper project! I must inform you that I'm moving my efforts from the archive explorer to the levels decompilation. The archive explorer will only work once I got nothing else to do.
For now, you can use Ripped Apart or similar mod managers/game files rippers to extract the interesting files.

Stay tuned, cordially, VELD-Dev.
